baseURL = "/status-page/"
languageCode = "en-us"
title = "System Status"
disableKinds = ["taxonomy", "term"]
publishDir = "docs"


[functions]
  [functions.toInt]
    params = ["value"]
    code = """
      return int(value)
    """

# Site parameters
[params]
  description = "Real-time system status and incident updates"
  mainSections = ['incidents']

[module]
  [[module.mounts]]
    source = "static"
    target = "static"

# Menu configuration
[menu]
  [[menu.main]]
    name = "Current Status"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Incident History"
    url = "/incidents/"
    weight = 2
  [[menu.main]]
    name = "Systems"
    url = "/systems/"
    weight = 3
