name: Branch Protection Rules

on:
  # This workflow is meant to run manually or on repository_dispatch
  workflow_dispatch:
  repository_dispatch:
    types: [configure-branch-protection]

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Branch Protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: ['build', 'test']  # Add your required status checks here
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true
              },
              restrictions: null,  // No restrictions on who can push
              allow_force_pushes: false,
              allow_deletions: false
            });

            // Also protect the gh-pages branch since it hosts our status page
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'gh-pages',
              required_status_checks: null,  // No status checks needed for gh-pages
              enforce_admins: true,
              required_pull_request_reviews: null,  // No reviews needed as this is automated
              restrictions: {
                users: [],
                teams: [],
                apps: ['github-actions']  // Only allow GitHub Actions to push
              },
              allow_force_pushes: false,
              allow_deletions: false
            });
